// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umaxfwxnlnasrpegmkuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtYXhmd3hubG5hc3JwZWdta3VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExODcwNzEsImV4cCI6MjA2Njc2MzA3MX0.yIksmyQS6302S0dFvp16-zS2_YbJqje-X5wQEYtHxmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);